---
namespace: "tcharl"
name: "ansible_libvirt_vm"
version: "1.0.1"
description: "Fork of StackHPC libvirt to run on fedora"

authors:
  - "Charlie Mordant <cmordant1@gmail.com>"

repository: "https://github.com/OsgiliathEnterprise/ansible-role-libvirt-vm"
documentation: "https://github.com/OsgiliathEnterprise/ansible-role-libvirt-vm"
homepage: "https://github.com/OsgiliathEnterprise/ansible-role-libvirt-vm"
issues: "https://github.com/OsgiliathEnterprise/ansible-role-libvirt-vm"

readme: "README.md"
license:
  - "Apache-2.0"
tags:
  - "linux"
  - "system"
  - "vm"
